/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical projects and is checked in here
// because the scaffold is created manually.
